version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4611:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000
      restart: unless-stopped

  py-app:
    build:
      context: ./python-app
      dockerfile: Dockerfile
    ports:
      - "4613:8000"
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    restart: unless-stopped
    command:
      - --storageEngine=wiredTiger
    volumes:
      - persfo-v3_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 4612:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root-persfo
      ME_CONFIG_BASICAUTH_PASSWORD: secret-persfo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example-persfo

volumes:
  persfo-v3_data:
